language: node_js

node_js:
  - "8"

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm install -g vuepress

script:
  - vuepress build .
  - touch .vuepress/dist/.nojekyll

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: .vuepress/dist/
    fqdn: "opencoin.dev"
    on:
      branch: master